#! /bin/bash
#
# This file is part of DisOrder.
# Copyright (C) 2004, 2005, 2006 Richard Kettlewell
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#

set -e
set -x
srcdir=$(dirname $0)
here=$(pwd)
cd $srcdir
rm -f COPYING
for f in /usr/share/common-licenses/GPL-2 $HOME/doc/GPL-2; do
  if test -e "$f"; then
    ln -s "$f" COPYING
    break
  fi
done
if test -d $HOME/share/aclocal; then
  aclocal --acdir=$HOME/share/aclocal
else
  aclocal
fi
libtoolize
autoconf
autoheader
automake -a || true		# for INSTALL
automake --foreign -a
cd "$here"
$srcdir/configure --sysconfdir=/etc --localstatedir=/var "$@"
