/* autogenerated file, do not edit */

 const char disorder_version_string[] = 
  "%s (DisOrder) 5.1.1\n"
  "Copyright (C) 2003-2011 Richard Kettlewell et al\n"
  "License GPLv3+: GNU GPL version 3 or later:\n"
  "        http://www.gnu.org/licenses/gpl-3.0.html\n"
  "This is free software: you are free to change and redistribute it.\n"
  "There is NO WARRANTY, to the extent permitted by law.\n"
;
