#! /bin/bash
#
# This file is part of DisOrder
# Copyright (C) 2005-2008 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
[ -d =build ] && cd =build
make
make distcheck
make dist-bzip2
d=$(make echo-distdir)
cp $d.tar.bz2 $HOME/work/web/disorder
cd doc
for f in *.[1-9].html; do
  echo $f
  rm -f $HOME/work/web/disorder/$f
  sed < $f > $HOME/work/web/disorder/$f 's/^@.*//'
done
cp plumbing.svg $HOME/work/web/disorder
cp plumbing.png $HOME/work/web/disorder
