#! /bin/bash
#
# Copyright (C) 2004, 2005 Richard Kettlewell
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#

set -e
buildhost=${buildhost:-lyonesse}
builddir=${builddir:-.}
make dist-bzip2
distdir=`make echo-distdir`
scp $distdir.tar.bz2 $buildhost:$builddir/$distdir.tar.bz2
ssh $buildhost "
  set -e
  set -x
  cd $builddir
  rm -rf $distdir
  tar xfj $distdir.tar.bz2
  cd $distdir
  CC='ccache cc' debian/rules build
  fakeroot debian/rules binary
"
# arch-tag:3ebf6ef38076b7cb313b86843e741d97
